receivers:
  tcplog:
    listen_address: "0.0.0.0:25888"
  udplog:
    listen_address: "0.0.0.0:25888"

exporters:
  awscloudwatchlogs:
    region: us-west-2
    raw_log: true
    log_group_name: SethTest
    log_stream_name: SethTest

  logging:

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    logs:
      receivers: [tcplog, udplog]
      processors: [batch]
      exporters: [awscloudwatchlogs, logging]
